#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


pidfile="/var/run/myscript.pid"

cleanup() {
    echo "Cleaning up and exiting..."
    rm -f "$pidfile"
    exit 0
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && cleanup' SIGTERM
trap 'cleanup' SIGQUIT

echo "$$" > "$pidfile"

while true
do
    echo "To infinity and beyond"
    sleep 2
done
