#!/usr/bin/env bash
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Displays Y U no love me?! when receiving a SIGINT signal


sudo bash -c "echo $$ > /var/run/myscript.pid"

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'sudo rm -f /var/run/myscript.pid; exit' SIGQUIT


while :
do
    echo "To infinity and beyond"
    sleep 2
done
